import Head from 'next/head'
import { useRouter } from 'next/router'
import React from 'react'
import detail from '@/data/animeDetail.json'
import Navbar from 'layouts/Navbar'
import Image from 'next/image'

const Anime = () => {
    const router = useRouter()
    const animeId = router.query.id
    return (
        <>
            <Head>
                <title>Anime { animeId }</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className='center'>
                <Image src={ detail.data.images.jpg.image_url } alt={ detail.data.title } />
                <h1 className='bg-green-500'>Anime { animeId }</h1>
            </main>
        </>
    )
}

export default Anime