import Head from 'next/head'
import { useRouter } from 'next/router'
import React from 'react'
import detail from '@/data/animeDetail.json'
import Image from 'next/image'
import Board from 'features/Anime/components/Board'
import Badge from 'features/Anime/components/Badge'
import Button from 'components/Button'

const Anime = () => {
    const router = useRouter()
    const animeId = router.query.id
    return (
        <>
            <Head>
                <title>MyAnime</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className='mx-auto px-4 pb-4 center flex-col max-w-5xl'>
                <div className='center flex-col gap-4 md:flex-row md:items-start'>
                    <Image src={ detail.data.images.jpg.large_image_url } alt={ detail.data.title } width={ 200 } height={ 200 } />
                    <article aria-labelledby='detail-title'>
                        <header >
                            <h1 id='detail-title' className='font-bold text-center md:text-start'>{ detail.data.title }</h1>
                            <div className='flex justify-center gap-2 mt-4 flex-wrap md:justify-start '>
                                { detail.data.genres.map(({ name }) => (
                                    <Badge key={ name } name={ name } />
                                )) }
                            </div>
                        </header>
                        <p className='my-4'>{ detail.data.synopsis }</p>
                        <footer className='flex gap-3 flex-wrap justify-center md:justify-start'>
                            <Board category='episodes' value={ detail.data.episodes } />
                            <Board category='popularity' value={ detail.data.popularity } />
                            <Board category='score' value={ `#${detail.data.score}` } />
                            <Board category='rank' value={ `#${detail.data.rank}` } />
                        </footer>
                    </article>
                </div>
                <Button extraClassName='mt-4 mr-auto' onClick={ () => { } }>BACK</Button>
            </main>
        </>
    )
}

export default Anime